version: '3.3'
networks:
    myNetwork:
        external:
            name: myNetwork
services:
    orderer:
        deploy:
            replicas: 1 
            restart_policy: 
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement: 
                constraints: 
                    - node.hostname == orderer.example.com
        image: hyperledger/fabric-orderer:latest
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        hostname: orderer.example.com
        environment:
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/config/genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/tls/ca.crt
        ports:
            - 7050:7050
        volumes:
            - /var/mynetwork/certs/crypto-config/ordererOrganizations/example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/config/:/var/hyperledger/config
        networks:
            myNetwork: 
                aliases: 
                    - orderer.example.com
